import { Toaster } from 'react-hot-toast';
import './globals.css';
import Providers from './store/Providers';

export const metadata = {
	title: 'Sunlift',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<Providers>
			<html lang='en'>
				<body>
					<Toaster position='top-center' reverseOrder={false} />
					{children}
				</body>
			</html>
		</Providers>
	);
}
